CREATE TABLE BOOK (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1,INCREMENT BY 1,NO MAXVALUE,NO CYCLE,ORDER),
    NAME VARCHAR(25) NOT NULL,
    PUBLICATION DATE NOT NULL WITH DEFAULT CURRENT_DATE,
    PRICE DECIMAL(8,2),
    CONSTRAINT PK_BOOK PRIMARY KEY (ID)
);